void desenhaMenu(int opcao);
void texturaMenu();
void desenhaCaixa(int y1, int y2);
void menuPausa(int opcao);
void menuInfo();
void desenhaOpcoes(int opcao);
void menuFinal(int opcao);
void desenhaJogar(int opcao);
void desenhaInfo(int opcao);
void desenhaSair(int opcao);
void desenhaVoltar(int opcao);
void desenhaContinuar(int opcao);
void desenhaReiniciar(int opcao);
void desenhaNoMeio();
void desenhaEmBaixo();
void desenhaEmCima();
void menuSair();
void menuReset();